@extends('crm.layout')

@section('title', 'Customers & Sales')

@section('header_actions')
    @if($selectedCustomer)
        <button class="cs-btn cs-btn-soft" type="button" onclick="openCustomerModal()"><i class="fas fa-user-plus"></i> Add Customer</button>
        <button class="cs-btn cs-btn-primary" type="button" onclick="openSaleModal()"><i class="fas fa-plus"></i> Add Sale</button>
    @else
        <button class="cs-btn cs-btn-primary" type="button" onclick="openCustomerModal()"><i class="fas fa-user-plus"></i> Add Customer</button>
    @endif
@endsection

@section('content')
<style>
    .cs-page{--cs-main:var(--primary-purple);--cs-soft:var(--primary-soft);--cs-shadow:var(--primary-shadow);color:#243147}
    .cs-btn{min-height:42px;padding:.65rem 1rem;border:0;border-radius:11px;display:inline-flex;align-items:center;justify-content:center;gap:.5rem;font-weight:800;cursor:pointer}
    .cs-btn-primary{background:var(--primary-purple,#6d5dfc);color:#fff;box-shadow:0 8px 20px var(--primary-shadow,rgba(109,93,252,.2))}.cs-btn-soft{background:var(--primary-soft,#f1efff);color:var(--primary-purple,#6d5dfc)}
    .cs-hero{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.35rem 1.5rem;background:linear-gradient(135deg,#fff,var(--cs-soft));border:1px solid #e4eaf1;border-radius:18px;margin-bottom:1rem;box-shadow:0 7px 22px rgba(15,23,42,.05)}
    .cs-hero h2{margin:0;font-size:1.35rem}.cs-muted{color:#91a0b7;font-size:.78rem}.cs-search{width:300px;max-width:100%;padding:.72rem .85rem;border:1.5px solid #dbe3ed;border-radius:11px;outline:0}.cs-search:focus,.cs-control:focus{border-color:var(--cs-main);box-shadow:0 0 0 3px var(--cs-shadow)}
    .cs-directory-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-bottom:1rem}.cs-directory-stat{display:flex;align-items:center;gap:1rem;min-height:104px;padding:1rem 1.2rem;background:#fff;border:1px solid #e5ebf2;border-radius:17px;box-shadow:0 7px 24px rgba(15,23,42,.05)}.cs-directory-stat-icon{width:52px;height:52px;flex:0 0 52px;display:flex;align-items:center;justify-content:center;border-radius:15px;font-size:1.2rem}.cs-directory-stat-copy span{display:block;color:#91a0b7;font-size:.69rem;font-weight:850;letter-spacing:.065em;text-transform:uppercase}.cs-directory-stat-copy strong{display:block;margin-top:.18rem;color:#111827;font-size:1.55rem;line-height:1.1}.cs-directory-stat-copy small{display:block;margin-top:.28rem;color:#10a875;font-size:.68rem;font-weight:800}
    .cs-table-wrap{overflow:auto;background:#fff;border:1px solid #e5ebf2;border-radius:16px;box-shadow:0 9px 28px rgba(15,23,42,.055)}.cs-table{width:100%;border-collapse:collapse;min-width:900px}.cs-table th{padding:.9rem 1rem;background:#f7f9fc;border-bottom:2px solid var(--cs-soft);color:#728097;text-align:left;font-size:.67rem;letter-spacing:.05em;text-transform:uppercase}.cs-table td{padding:.95rem 1rem;border-bottom:1px solid #edf1f5;font-size:.82rem;vertical-align:middle}.cs-table tbody tr:hover{background:var(--cs-soft)}
    .cs-person{display:flex;align-items:center;gap:.7rem}.cs-avatar{width:38px;height:38px;display:flex;align-items:center;justify-content:center;border-radius:11px;background:var(--cs-soft);color:var(--cs-main);font-weight:900}.cs-person strong{display:block;color:#1f2b3d}.cs-link{display:inline-flex;align-items:center;gap:.4rem;padding:.43rem .7rem;border:1px solid var(--cs-shadow);border-radius:9px;text-decoration:none;color:var(--cs-main);font-weight:800}.cs-link:hover{background:var(--cs-main);color:#fff}
    .cs-back{display:inline-flex;align-items:center;gap:.45rem;margin-bottom:.8rem;color:var(--cs-main);text-decoration:none;font-weight:800}.cs-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-bottom:1rem}.cs-stat{padding:1rem 1.1rem;background:#fff;border:1px solid #e5ebf2;border-radius:15px;box-shadow:0 6px 18px rgba(15,23,42,.045)}.cs-stat span{display:block;color:#8695aa;font-size:.68rem;font-weight:800;text-transform:uppercase}.cs-stat strong{display:block;margin-top:.45rem;font-size:1.15rem;color:#1f2937}.cs-status{display:inline-flex;padding:.32rem .6rem;border-radius:999px;background:var(--cs-soft);color:var(--cs-main);font-weight:800;font-size:.7rem}.cs-pay{display:flex;align-items:center;gap:.35rem}.cs-pay input{width:90px}.cs-icon-btn{width:34px;height:34px;border:0;border-radius:9px;background:var(--cs-main);color:#fff;cursor:pointer}
    .cs-toolbar{display:flex;gap:.65rem;align-items:center;margin-bottom:.85rem}.cs-toolbar form{display:flex;gap:.55rem;flex:1}.cs-control{width:100%;padding:.66rem .75rem;border:1.5px solid #dce4ee;border-radius:10px;background:#fff;outline:0;box-sizing:border-box}.cs-modal-bg{position:fixed;inset:0;background:rgba(15,23,42,.55);display:none;align-items:center;justify-content:center;padding:1rem;z-index:9999}.cs-modal{width:100%;max-width:850px;max-height:92vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 24px 65px rgba(15,23,42,.25)}.cs-modal-head{display:flex;justify-content:space-between;align-items:center;padding:1rem 1.2rem;border-bottom:1px solid #edf1f5}.cs-modal-title{display:flex;align-items:center;gap:.75rem}.cs-modal-icon{width:40px;height:40px;border-radius:12px;display:flex;align-items:center;justify-content:center;background:var(--cs-main);color:#fff}.cs-modal h3{margin:0}.cs-close{border:0;background:#f1f5f9;width:34px;height:34px;border-radius:9px;cursor:pointer}.cs-form{padding:1.1rem}.cs-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:.8rem}.cs-field{grid-column:span 4}.cs-field-6{grid-column:span 6}.cs-field-12{grid-column:1/-1}.cs-field label{display:block;margin-bottom:.35rem;color:#475569;font-size:.72rem;font-weight:800}.cs-actions{display:flex;justify-content:flex-end;gap:.65rem;margin-top:1rem;padding-top:1rem;border-top:1px solid #edf1f5}.cs-totals{grid-column:1/-1;display:grid;grid-template-columns:repeat(4,1fr);padding:.8rem;border-radius:12px;background:var(--cs-soft);border:1px solid var(--cs-shadow)}.cs-totals span{display:block;color:#728097;font-size:.67rem;text-transform:uppercase;font-weight:800}.cs-totals strong{display:block;margin-top:.3rem;color:var(--cs-main)}.cs-empty{text-align:center!important;padding:2rem!important;color:#94a3b8}
    @media(max-width:800px){.cs-stats{grid-template-columns:repeat(2,1fr)}.cs-directory-stats{grid-template-columns:1fr}.cs-hero{align-items:flex-start;flex-direction:column}.cs-search{width:100%}.cs-field,.cs-field-6{grid-column:1/-1}}
</style>

<div class="cs-page">
@if(!$selectedCustomer)
    <div class="cs-hero">
        <div><h2>Customer Directory</h2><div class="cs-muted">Add a customer first, then record sales and payments against that customer.</div></div>
        <input id="customerSearch" class="cs-search" placeholder="Search customer, company, country..." oninput="filterCustomers(this.value)">
    </div>
    <div class="cs-directory-stats">
        <div class="cs-directory-stat"><span class="cs-directory-stat-icon" style="color:var(--cs-main);background:var(--cs-soft)"><i class="fas fa-users"></i></span><div class="cs-directory-stat-copy"><span>Total Customers</span><strong>{{ number_format($directorySummary['customers']) }}</strong><small>Customer profiles</small></div></div>
        <div class="cs-directory-stat"><span class="cs-directory-stat-icon" style="color:#059669;background:#e1f8ef"><i class="fas fa-shopping-bag"></i></span><div class="cs-directory-stat-copy"><span>Total Orders</span><strong>{{ number_format($directorySummary['orders']) }}</strong><small>Recorded customer sales</small></div></div>
        <div class="cs-directory-stat"><span class="cs-directory-stat-icon" style="color:#2563eb;background:#e8f1ff"><i class="fas fa-chart-line"></i></span><div class="cs-directory-stat-copy"><span>Avg. Order Value</span><strong>{{ number_format($directorySummary['average_order'],2) }}</strong><small>Per recorded order</small></div></div>
    </div>
    <div class="cs-table-wrap">
        <table class="cs-table" id="customersTable">
            <thead><tr><th>Customer</th><th>Country</th><th>Phone</th><th>Email</th><th>Orders</th><th>Total Sales</th><th>Outstanding</th><th>Action</th></tr></thead>
            <tbody>
            @forelse($customers as $customer)
                <tr data-search="{{ strtolower($customer->name.' '.$customer->company_name.' '.$customer->country.' '.$customer->phone.' '.$customer->email) }}">
                    <td><div class="cs-person"><span class="cs-avatar">{{ strtoupper(substr($customer->name,0,1)) }}</span><div><strong>{{ $customer->name }}</strong><div class="cs-muted">{{ $customer->company_name ?: 'Customer #'.str_pad($customer->id,4,'0',STR_PAD_LEFT) }}</div></div></div></td>
                    <td>{{ $customer->country ?: '-' }}</td><td>{{ $customer->phone ?: '-' }}</td><td>{{ $customer->email ?: '-' }}</td>
                    <td>{{ $customer->sales_count }}</td><td>{{ $customer->currency }} {{ number_format($customer->sales->sum('total_amount'),2) }}</td><td>{{ $customer->currency }} {{ number_format($customer->sales->sum('balance_amount'),2) }}</td>
                    <td><a class="cs-link" href="{{ route('crm.customer_sales.index',['customer_id'=>$customer->id]) }}">View Sales <i class="fas fa-arrow-right"></i></a></td>
                </tr>
            @empty
                <tr><td colspan="8" class="cs-empty">No customers yet. Click “Add Customer” to create the first customer.</td></tr>
            @endforelse
            </tbody>
        </table>
    </div>
@else
    <a class="cs-back" href="{{ route('crm.customer_sales.index') }}"><i class="fas fa-arrow-left"></i> All Customers</a>
    <div class="cs-hero"><div><h2>{{ $selectedCustomer->name }}</h2><div class="cs-muted">{{ $selectedCustomer->company_name }} · {{ $selectedCustomer->country }} · {{ $selectedCustomer->email }}</div></div><span class="cs-status">{{ $selectedCustomer->currency }}</span></div>
    <div class="cs-stats">
        <div class="cs-stat"><span>Total Sales</span><strong>{{ $selectedCustomer->currency }} {{ number_format($summary['total'],2) }}</strong></div>
        <div class="cs-stat"><span>Amount Received</span><strong>{{ $selectedCustomer->currency }} {{ number_format($summary['paid'],2) }}</strong></div>
        <div class="cs-stat"><span>Outstanding</span><strong>{{ $selectedCustomer->currency }} {{ number_format($summary['balance'],2) }}</strong></div>
        <div class="cs-stat"><span>Open Orders</span><strong>{{ $summary['open_count'] }}</strong></div>
    </div>
    <div class="cs-toolbar"><form method="GET"><input type="hidden" name="customer_id" value="{{ $selectedCustomer->id }}"><input class="cs-control" name="search" value="{{ request('search') }}" placeholder="Search order or item..."><select class="cs-control" name="payment_status" onchange="this.form.submit()"><option value="">All payments</option>@foreach(['Unpaid','Partial','Paid'] as $status)<option {{ request('payment_status')===$status?'selected':'' }}>{{ $status }}</option>@endforeach</select><button class="cs-btn cs-btn-soft">Search</button></form></div>
    <div class="cs-table-wrap"><table class="cs-table"><thead><tr><th>Date</th><th>Order</th><th>Item</th><th>Qty</th><th>Total</th><th>Paid / Balance</th><th>Order Status</th><th>Payment</th><th>Action</th></tr></thead><tbody>
    @forelse($sales as $sale)
        <tr><td>{{ $sale->order_date->format('d M Y') }}</td><td><strong>{{ $sale->order_number }}</strong></td><td>{{ $sale->item_name }}</td><td>{{ number_format($sale->quantity,2) }} {{ $sale->unit }}</td><td>{{ $sale->currency }} {{ number_format($sale->total_amount,2) }}</td><td>{{ number_format($sale->paid_amount,2) }} / {{ number_format($sale->balance_amount,2) }}</td><td><span class="cs-status">{{ $sale->order_status }}</span></td><td><form class="cs-pay" method="POST" action="{{ route('crm.customer_sales.update_payment',$sale->id) }}">{{ csrf_field() }}{{ method_field('PATCH') }}<input class="cs-control" name="paid_amount" type="number" step=".01" min="0" max="{{ $sale->total_amount }}" value="{{ $sale->paid_amount }}"><button class="cs-icon-btn"><i class="fas fa-save"></i></button></form></td><td><button class="cs-icon-btn" type="button" onclick="editSale({{ $sale->id }})"><i class="fas fa-edit"></i></button></td></tr>
    @empty<tr><td colspan="9" class="cs-empty">No sales recorded for this customer.</td></tr>@endforelse
    </tbody></table></div>
    @if(method_exists($sales,'links')) {{ $sales->links() }} @endif
@endif
</div>

<div class="cs-modal-bg" id="customerModal" onclick="if(event.target===this)closeCustomerModal()"><div class="cs-modal" style="max-width:720px"><div class="cs-modal-head"><div class="cs-modal-title"><span class="cs-modal-icon"><i class="fas fa-user-plus"></i></span><div><h3>Add Customer</h3><div class="cs-muted">Customer profile is saved separately for the active project.</div></div></div><button class="cs-close" onclick="closeCustomerModal()"><i class="fas fa-times"></i></button></div><form class="cs-form" method="POST" action="{{ route('crm.customers.store') }}">{{ csrf_field() }}<div class="cs-grid">
    <div class="cs-field-6"><label>Customer Name *</label><input class="cs-control" name="name" required></div><div class="cs-field-6"><label>Company</label><input class="cs-control" name="company_name"></div>
    <div class="cs-field"><label>Phone</label><input class="cs-control" name="phone"></div><div class="cs-field"><label>Email</label><input class="cs-control" type="email" name="email"></div><div class="cs-field"><label>Country *</label><select class="cs-control" name="country" id="customerCountry" required><option value="">Select country</option></select></div>
    <div class="cs-field"><label>Currency *</label><select class="cs-control" name="currency" id="customerCurrency" required>@foreach(['AED','USD','GBP','EUR','PKR','SAR','QAR','OMR','KWD','CAD','AUD'] as $currency)<option>{{ $currency }}</option>@endforeach</select></div><div class="cs-field"><label>TRN / Tax Number</label><input class="cs-control" name="tax_number"></div>
    <div class="cs-field-6"><label>Billing Address</label><textarea class="cs-control" name="billing_address"></textarea></div><div class="cs-field-6"><label>Shipping Address</label><textarea class="cs-control" name="shipping_address"></textarea></div><div class="cs-field-12"><label>Notes</label><textarea class="cs-control" name="notes"></textarea></div>
</div><div class="cs-actions"><button class="cs-btn cs-btn-soft" type="button" onclick="closeCustomerModal()">Cancel</button><button class="cs-btn cs-btn-primary">Save Customer</button></div></form></div></div>

@if($selectedCustomer)
<div class="cs-modal-bg" id="saleModal" onclick="if(event.target===this)closeSaleModal()"><div class="cs-modal"><div class="cs-modal-head"><div class="cs-modal-title"><span class="cs-modal-icon"><i class="fas fa-file-invoice-dollar"></i></span><div><h3 id="saleModalTitle">Add Customer Sale</h3><div class="cs-muted">{{ $selectedCustomer->name }}</div></div></div><button class="cs-close" onclick="closeSaleModal()"><i class="fas fa-times"></i></button></div><form class="cs-form" id="saleForm" method="POST" action="{{ route('crm.customer_sales.store') }}">{{ csrf_field() }}<input id="saleMethod" type="hidden" name="_method" value="POST"><input type="hidden" name="customer_id" value="{{ $selectedCustomer->id }}"><div class="cs-grid">
    <div class="cs-field"><label>Order Number *</label><input class="cs-control" name="order_number" value="SO-{{ date('ymd-His') }}" required></div><div class="cs-field"><label>Order Date *</label><input class="cs-control" type="date" name="order_date" value="{{ date('Y-m-d') }}" required></div><div class="cs-field"><label>Due Date</label><input class="cs-control" type="date" name="due_date"></div>
    <div class="cs-field-6"><label>Product / Item *</label><input class="cs-control" name="item_name" required></div><div class="cs-field-6"><label>Description</label><input class="cs-control" name="description"></div>
    <div class="cs-field"><label>Quantity *</label><input class="cs-control cs-calc" type="number" step=".01" min=".01" name="quantity" value="1" required></div><div class="cs-field"><label>Unit</label><select class="cs-control" name="unit">@foreach(['Pieces','Boxes','Sheets','Rolls','Kg','Sets','Units'] as $unit)<option>{{ $unit }}</option>@endforeach</select></div><div class="cs-field"><label>Unit Price *</label><input class="cs-control cs-calc" type="number" step=".01" min="0" name="unit_price" value="0" required></div>
    <div class="cs-field"><label>Discount</label><input class="cs-control cs-calc" type="number" step=".01" min="0" name="discount_amount" value="0"></div><div class="cs-field"><label>Tax</label><input class="cs-control cs-calc" type="number" step=".01" min="0" name="tax_amount" value="0"></div><div class="cs-field"><label>Shipping</label><input class="cs-control cs-calc" type="number" step=".01" min="0" name="shipping_cost" value="0"></div>
    <div class="cs-field"><label>Paid Amount</label><input class="cs-control cs-calc" type="number" step=".01" min="0" name="paid_amount" value="0"></div><div class="cs-field"><label>Currency</label><select class="cs-control" name="currency">@foreach(['AED','USD','GBP','EUR','PKR','SAR','QAR','OMR','KWD','CAD','AUD'] as $currency)<option {{ $selectedCustomer->currency===$currency?'selected':'' }}>{{ $currency }}</option>@endforeach</select></div><div class="cs-field"><label>Payment Method</label><select class="cs-control" name="payment_method"><option value="">Select</option>@foreach(['Cash','Bank Transfer','Card','Cheque','Credit'] as $method)<option>{{ $method }}</option>@endforeach</select></div>
    <div class="cs-field"><label>Order Status</label><select class="cs-control" name="order_status">@foreach(['Draft','Confirmed','In Production','Ready','Dispatched','Delivered','Completed','On Hold','Cancelled'] as $status)<option>{{ $status }}</option>@endforeach</select></div><div class="cs-field-12"><label>Notes</label><textarea class="cs-control" name="notes"></textarea></div>
    <div class="cs-totals"><div><span>Subtotal</span><strong id="csSubtotal">0.00</strong></div><div><span>Total</span><strong id="csTotal">0.00</strong></div><div><span>Balance</span><strong id="csBalance">0.00</strong></div><div><span>Payment</span><strong id="csPaymentStatus">Unpaid</strong></div></div>
</div><div class="cs-actions"><button class="cs-btn cs-btn-soft" type="button" onclick="closeSaleModal()">Cancel</button><button class="cs-btn cs-btn-primary">Save Sale</button></div></form></div></div>
@endif
@endsection

@section('scripts')
<script>
function filterCustomers(value){var q=(value||'').toLowerCase().trim();document.querySelectorAll('#customersTable tbody tr[data-search]').forEach(function(row){row.style.display=!q||(row.getAttribute('data-search')||'').indexOf(q)!==-1?'table-row':'none'})}
function openCustomerModal(){document.getElementById('customerModal').style.display='flex';document.body.style.overflow='hidden'}function closeCustomerModal(){document.getElementById('customerModal').style.display='none';document.body.style.overflow=''}
(function(){var select=document.getElementById('customerCountry');if(!select)return;var fallback=['United Arab Emirates','United States','United Kingdom','Pakistan','Saudi Arabia','Qatar','Oman','Kuwait','Bahrain','Canada','Australia','India','China','Germany','France'];function render(list){select.innerHTML='<option value="">Select country</option>';list.sort().forEach(function(name){var option=document.createElement('option');option.value=name;option.textContent=name;select.appendChild(option)})}fetch('https://restcountries.com/v3.1/all?fields=name').then(function(r){return r.json()}).then(function(rows){render(rows.map(function(row){return row.name.common}))}).catch(function(){render(fallback)})})();
@if($selectedCustomer)
var customerSales=@json($sales->getCollection()->keyBy('id'));
function openSaleModal(){var form=document.getElementById('saleForm');form.reset();form.action='{{ route('crm.customer_sales.store') }}';document.getElementById('saleMethod').value='POST';document.getElementById('saleModalTitle').textContent='Add Customer Sale';form.elements.customer_id.value='{{ $selectedCustomer->id }}';form.elements.order_date.value='{{ date('Y-m-d') }}';form.elements.currency.value='{{ $selectedCustomer->currency }}';document.getElementById('saleModal').style.display='flex';document.body.style.overflow='hidden';calculateSale()}
function closeSaleModal(){document.getElementById('saleModal').style.display='none';document.body.style.overflow=''}
function editSale(id){var data=customerSales[id];if(!data)return;var form=document.getElementById('saleForm');form.reset();form.action='{{ url('/crm/customer-sales') }}/'+id;document.getElementById('saleMethod').value='PUT';document.getElementById('saleModalTitle').textContent='Edit Customer Sale';Object.keys(data).forEach(function(name){var field=form.elements[name];if(!field)return;var value=data[name];if((name==='order_date'||name==='due_date')&&value)value=String(value).substring(0,10);field.value=value===null?'':value});document.getElementById('saleModal').style.display='flex';document.body.style.overflow='hidden';calculateSale()}
function calculateSale(){var f=document.getElementById('saleForm');if(!f)return;var n=function(name){return parseFloat(f.elements[name].value)||0},subtotal=n('quantity')*n('unit_price'),total=Math.max(0,subtotal-n('discount_amount')+n('tax_amount')+n('shipping_cost')),paid=n('paid_amount'),balance=Math.max(0,total-paid);document.getElementById('csSubtotal').textContent=subtotal.toFixed(2);document.getElementById('csTotal').textContent=total.toFixed(2);document.getElementById('csBalance').textContent=balance.toFixed(2);document.getElementById('csPaymentStatus').textContent=paid<=0?'Unpaid':(balance>0?'Partial':'Paid')}
document.querySelectorAll('.cs-calc').forEach(function(field){field.addEventListener('input',calculateSale)});
@endif
</script>
@endsection
