@php
    $paperDimensionUnit = strtolower(trim((string)(optional($ticket->lead)->unit ?: ($ticket->unit ?: 'mm'))));
    $paperDimensionUnit = in_array($paperDimensionUnit, ['inch', 'in', 'inches'], true) ? 'inches' : $paperDimensionUnit;
    $paperDimensionLabel = $paperDimensionUnit === 'cm' ? 'Centimetres (cm)'
        : ($paperDimensionUnit === 'inches' ? 'Inches (in)' : 'Millimetres (mm)');
    $paperCalculatorState = is_array($calculatorState['paper'] ?? null) ? $calculatorState['paper'] : [];
@endphp
<style>
.pc-card{overflow:hidden}.pc-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;margin-bottom:1.15rem}.pc-heading h3{margin-bottom:.25rem}.pc-kicker{color:#8a98aa;font-size:.72rem;line-height:1.45}.pc-badge{display:inline-flex;align-items:center;gap:.4rem;padding:.42rem .65rem;border:1px solid #dce5ee;border-radius:999px;background:#f7f9fc;color:#6a7a90;font-size:.62rem;font-weight:850;white-space:nowrap}.pc-badge i{color:#14a36f}.pc-message{display:none;align-items:center;gap:.45rem;margin-top:.75rem;padding:.62rem .75rem;border-radius:9px;font-size:.68rem;font-weight:750}.pc-message.show{display:flex}.pc-message.error{border:1px solid #fecaca;background:#fff1f2;color:#b91c1c}.pc-message.success{border:1px solid #bbf7d0;background:#f0fdf4;color:#15803d}
.pc-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem;padding:1rem;border:1px solid #e3e9f1;border-radius:14px;background:#f7f9fc}.pc-field{position:relative}.pc-field label,.pc-result span{display:block;margin-bottom:.32rem;color:#8290a4;font-size:.61rem;font-weight:850;text-transform:uppercase;letter-spacing:.06em}.pc-field small{display:block;margin-top:.3rem;color:#9aa6b6;font-size:.59rem}.pc-results{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.65rem;margin-top:1rem}.pc-result{min-height:82px;padding:.8rem .85rem;border:1px solid #e2e8f0;border-radius:11px;background:#fff}.pc-result strong{color:#233047;font-size:.86rem;font-variant-numeric:tabular-nums}.pc-result.final{position:relative;overflow:hidden;background:linear-gradient(135deg,var(--primary-soft),#fff);border-color:var(--primary-shadow)}.pc-result.final:after{content:"";position:absolute;right:-22px;bottom:-27px;width:70px;height:70px;border-radius:50%;background:var(--primary-shadow);opacity:.35}.pc-result.final strong{position:relative;z-index:1;color:var(--primary-purple);font-size:1.08rem}.pc-actions{display:flex;gap:.5rem;justify-content:flex-end;flex-wrap:wrap;margin-top:1rem;padding-top:1rem;border-top:1px solid #edf1f5}.pc-actions .es-primary{min-width:145px}.pc-stale{display:none;margin-top:.75rem;padding:.6rem .75rem;border:1px solid #fed7aa;border-radius:9px;background:#fff7ed;color:#c2410c;font-size:.68rem;font-weight:750}.pc-card.stale .pc-results{opacity:.42;filter:grayscale(.3)}.pc-card.stale .pc-stale{display:block}
@media(max-width:1100px){.pc-grid{grid-template-columns:repeat(3,1fr)}.pc-results{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.pc-grid{grid-template-columns:repeat(2,1fr)}.pc-heading{flex-direction:column}.pc-badge{align-self:flex-start}}@media(max-width:520px){.pc-grid,.pc-results{grid-template-columns:1fr}.pc-actions .es-btn{width:100%}}
</style>
<div class="es-card pc-card" id="paperCalculator">
    <div class="pc-heading">
        <div><h3><i class="fas fa-file-alt"></i> Paper Cost Calculator</h3><div class="pc-kicker">Enter sheet specifications and purchase pricing to calculate the landed paper cost.</div></div>
        <span class="pc-badge"><i class="fas fa-shield-alt"></i> Live calculation</span>
    </div>
    <div class="pc-grid">
        <div class="pc-field"><label for="pcLength">Sheet Length</label><input class="es-input pc-input" id="pcLength" form="professionalEstimateForm" name="calculator_state[paper][length]" value="{{ $paperCalculatorState['length'] ?? '' }}" type="number" min="0" step=".01"><small>{{ $paperDimensionLabel }}</small></div>
        <div class="pc-field"><label for="pcWidth">Sheet Width</label><input class="es-input pc-input" id="pcWidth" form="professionalEstimateForm" name="calculator_state[paper][width]" value="{{ $paperCalculatorState['width'] ?? '' }}" type="number" min="0" step=".01"><small>{{ $paperDimensionLabel }}</small></div>
        <div class="pc-field"><label for="pcGsm">Paper Weight</label><input class="es-input pc-input" id="pcGsm" form="professionalEstimateForm" name="calculator_state[paper][gsm]" value="{{ $paperCalculatorState['gsm'] ?? '' }}" type="number" min="0" step=".01" placeholder="e.g. 350"><small>Grams per square metre</small></div>
        <div class="pc-field"><label for="pcQty">Required Quantity</label><input class="es-input pc-input" id="pcQty" form="professionalEstimateForm" name="calculator_state[paper][quantity]" value="{{ $paperCalculatorState['quantity'] ?? '' }}" type="number" min="1"><small>Number of sheets</small></div>
        <div class="pc-field"><label for="pcPrice">Purchase Price</label><input class="es-input pc-input" id="pcPrice" form="professionalEstimateForm" name="calculator_state[paper][price]" value="{{ $paperCalculatorState['price'] ?? '' }}" type="number" min="0" step=".0001" placeholder="0.00"><small>Supplier price before VAT</small></div>
        <div class="pc-field"><label>Priced By</label><select class="es-input pc-input" id="pcPricedBy" form="professionalEstimateForm" name="calculator_state[paper][priced_by]"><option value="sheet" {{ ($paperCalculatorState['priced_by'] ?? 'sheet') === 'sheet' ? 'selected' : '' }}>Per Sheet</option><option value="ream" {{ ($paperCalculatorState['priced_by'] ?? '') === 'ream' ? 'selected' : '' }}>Per Ream (500)</option></select></div>
        <div class="pc-field"><label>Price Entered In</label><select class="es-input pc-input" id="pcCurrency" form="professionalEstimateForm" name="calculator_state[paper][currency]"><option {{ ($paperCalculatorState['currency'] ?? (($ticket->currency ?: 'USD') === 'USD' ? 'USD' : 'AED')) === 'AED' ? 'selected' : '' }}>AED</option><option {{ ($paperCalculatorState['currency'] ?? (($ticket->currency ?: 'USD') === 'USD' ? 'USD' : 'AED')) === 'USD' ? 'selected' : '' }}>USD</option></select></div>
        <div class="pc-field"><label>Wastage / Trim %</label><input class="es-input pc-input" id="pcWaste" form="professionalEstimateForm" name="calculator_state[paper][waste]" type="number" min="0" step=".01" value="{{ $paperCalculatorState['waste'] ?? '' }}"></div>
        <div class="pc-field"><label>VAT %</label><input class="es-input pc-input" id="pcVat" form="professionalEstimateForm" name="calculator_state[paper][vat]" type="number" min="0" step="0.01" value="{{ $paperCalculatorState['vat'] ?? old('vat_percentage', (float)(optional($ticket->lead)->vat_percentage ?: 5)) }}"></div>
    </div>
    <div class="pc-stale"><i class="fas fa-exclamation-circle"></i> Inputs changed — press Update Price.</div>
    <div class="pc-message" id="pcMessage" role="status" aria-live="polite"></div>
    <div class="pc-results">
        <div class="pc-result"><span>Price / Sheet</span><strong id="pcPerSheet">—</strong></div>
        <div class="pc-result"><span>Subtotal</span><strong id="pcSubtotal">—</strong></div><div class="pc-result"><span>VAT</span><strong id="pcVatAmount">—</strong></div>
        <div class="pc-result final"><span>Final Price</span><strong id="pcFinal">—</strong></div>
    </div>
    <div class="pc-actions"><button class="es-btn" type="button" id="pcCopy"><i class="fas fa-copy"></i> Copy Quote</button>@if($canEditEstimate)<button class="es-btn" type="button" id="pcUse"><i class="fas fa-arrow-down"></i> Use as Paper Cost</button>@endif<button class="es-btn es-primary" type="button" id="pcCalculate"><i class="fas fa-calculator"></i> Calculate Price</button></div>
</div>
<script>
(function(){
var card=document.getElementById('paperCalculator'),button=document.getElementById('pcCalculate'),message=document.getElementById('pcMessage'),result=null,messageTimer=null;
var dimensionUnit={!! json_encode($paperDimensionUnit) !!},metresPerUnit=dimensionUnit==='cm'?0.01:(dimensionUnit==='inches'?0.0254:0.001);
function n(id){return Number(document.getElementById(id).value||0)}function money(v,c){return c+' '+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function showMessage(text,type){clearTimeout(messageTimer);message.className='pc-message show '+type;message.innerHTML='<i class="fas '+(type==='success'?'fa-check-circle':'fa-exclamation-circle')+'"></i>'+text;messageTimer=setTimeout(clearMessage,2000)}
function clearMessage(){clearTimeout(messageTimer);message.className='pc-message';message.textContent=''}
function stale(){clearMessage();if(result){card.classList.add('stale');button.innerHTML='<i class="fas fa-sync-alt"></i> Update Price'}}
document.querySelectorAll('.pc-input').forEach(function(i){i.addEventListener('input',stale);i.addEventListener('change',stale);i.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();button.click()}})});
button.addEventListener('click',function(){clearMessage();var l=n('pcLength'),w=n('pcWidth'),gsm=n('pcGsm'),qty=n('pcQty'),price=n('pcPrice');if(!l||!w||!gsm||!qty){showMessage('Enter a valid length, width, GSM and sheet quantity to continue.','error');return}var grams=l*metresPerUnit*w*metresPerUnit*gsm,kg=grams/1000,by=document.getElementById('pcPricedBy').value,sheet=price;if(by==='ream')sheet=price/500;var currency=document.getElementById('pcCurrency').value,subtotal=sheet*qty*(1+n('pcWaste')/100),vat=subtotal*n('pcVat')/100,total=subtotal+vat,perKg=sheet/kg;result={l:l,w:w,unit:dimensionUnit,gsm:gsm,qty:qty,grams:grams,totalKg:kg*qty,currency:currency,sheet:sheet,subtotal:subtotal,vat:vat,total:total,perKg:perKg};document.getElementById('pcPerSheet').textContent=money(sheet,currency);document.getElementById('pcSubtotal').textContent=money(subtotal,currency);document.getElementById('pcVatAmount').textContent=money(vat,currency);document.getElementById('pcFinal').textContent=money(total,currency);card.classList.remove('stale');button.innerHTML='<i class="fas fa-sync-alt"></i> Update Price';showMessage('Paper price calculated successfully.','success')});
document.getElementById('pcCopy').addEventListener('click',function(){if(!result||card.classList.contains('stale')){showMessage('Calculate the latest price before copying the quote.','error');return}var text='Paper Quote\\nSize: '+result.l+' × '+result.w+' '+result.unit+'\\nGSM: '+result.gsm+'\\nQuantity: '+result.qty+' sheets\\nWeight/sheet: '+result.grams.toFixed(2)+' g\\nTotal: '+money(result.total,result.currency);if(navigator.clipboard){navigator.clipboard.writeText(text).then(function(){showMessage('Quote copied to clipboard.','success')}).catch(function(){window.prompt('Copy quote:',text)})}else window.prompt('Copy quote:',text)});
var use=document.getElementById('pcUse');if(use)use.addEventListener('click',function(){if(!result||card.classList.contains('stale')){showMessage('Calculate the latest price before using this cost.','error');return}var estimate=selectedCurrency();if(estimate!==result.currency){showMessage('Calculator currency must match the estimate currency ('+estimate+').','error');return}var name=Array.prototype.slice.call(document.querySelectorAll('input[name="cost_names[]"]')).filter(function(i){return i.value==='Paper Dimensions'})[0];if(!name){showMessage('The Paper Cost row could not be found.','error');return}var row=name.closest('tr'),input=row.querySelector('.cost-price'),quantityInput=row.querySelector('.cost-quantity'),unitPriceInput=row.querySelector('.cost-unit-price'),detail=result.l+' × '+result.w+' '+result.unit+' · '+result.gsm+' GSM',detailInput=row.querySelector('input[name="cost_details[]"]'),detailText=row.querySelector('.cost-detail-text'),vatInput=document.getElementById('estimateVatPercentage');if(quantityInput)quantityInput.value=result.qty;if(unitPriceInput)unitPriceInput.value=(result.qty>0?result.total/result.qty:0).toFixed(4);input.value=result.total.toFixed(2);if(detailInput)detailInput.value=detail;if(detailText)detailText.textContent=detail;if(vatInput)vatInput.value=n('pcVat').toFixed(2);input.dispatchEvent(new Event('input'));showMessage('Paper cost, specification and VAT added to the professional estimate.','success');row.scrollIntoView({behavior:'smooth',block:'center'})});
})();
</script>
