@extends('crm.layout')
@section('title', 'Get Estimate')
@section('content')
@php $u = Auth::guard('crm')->user(); @endphp
<style>
.et-card{background:#fff;border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 5px 16px rgba(15,23,42,.05);overflow:hidden}.et-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:.65rem 1rem;border-radius:9px;text-decoration:none;border:1px solid #dbe3ef;background:#fff;color:#475569;font-weight:700;cursor:pointer}.et-primary{background:var(--primary-purple);color:#fff;border-color:var(--primary-purple)}.et-tabs{display:flex;gap:.55rem;margin-bottom:1rem;flex-wrap:wrap}.et-tab{display:inline-flex;align-items:center;gap:.45rem;padding:.62rem .85rem;border-radius:10px;background:#edf2f7;color:#526176;text-decoration:none;font-weight:850}.et-tab.active{background:var(--primary-purple);color:#fff}.et-tab-count{min-width:21px;height:21px;padding:0 5px;display:inline-flex;align-items:center;justify-content:center;border-radius:99px;background:rgba(255,255,255,.22);font-size:.67rem}.et-table{width:100%;border-collapse:collapse}.et-table th{padding:1rem;background:#f8fafc;color:#64748b;text-align:left;font-size:.75rem;text-transform:uppercase}.et-table td{padding:1rem;border-top:1px solid #f1f5f9;color:#334155}.et-ticket-row{transition:background-color .16s ease,box-shadow .16s ease}.et-ticket-row:hover{background:var(--primary-soft);box-shadow:inset 4px 0 0 var(--primary-purple)}.et-status{padding:.3rem .65rem;border-radius:99px;font-size:.74rem;font-weight:800}.s-pending{background:#fff7ed;color:#c2410c}.s-open,.s-team_lead_open{background:#eaf2ff;color:#285fbd}.s-team_lead_review{background:#ecfeff;color:#0e7490}.s-estimated{background:#ecfdf5;color:#047857}.s-revision_requested{background:#fef2f2;color:#dc2626}.s-completed{background:#eef2ff;color:var(--primary-purple)}.s-owner_review{background:#fdf4ff;color:#a21caf}
</style>
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1.25rem;gap:1rem;flex-wrap:wrap">
 <div><h2 style="margin:0;color:#0f172a">Estimate Tickets</h2><p style="margin:.3rem 0 0;color:#64748b">Multiple quantities and delivery dates in one request.</p></div>
 @if(!$u->isEstimator())<a class="et-btn et-primary" href="{{ route('crm.estimate_tickets.create') }}"><i class="fas fa-plus"></i> New Estimate Request</a>@endif
</div>
<div class="et-tabs">
    <a class="et-tab {{ $tab==='active'?'active':'' }}" href="{{ route('crm.estimate_tickets.index',['tab'=>'active']) }}"><i class="fas fa-layer-group"></i> Active Tickets <span class="et-tab-count">{{ $activeCount }}</span></a>
    @php $__isAlMassaAdmin = $u->isAdmin() && optional($activeCrmWorkspace)->slug === 'mybox-packaging-app'; @endphp
    @if($u->isEstimator() || $u->isTeamLead() || $__isAlMassaAdmin)
        <a class="et-tab {{ $tab==='mine'?'active':'' }}" href="{{ route('crm.estimate_tickets.index',['tab'=>'mine']) }}"><i class="fas fa-folder-open"></i> {{ $__isAlMassaAdmin && !$u->isEstimator() ? 'Open Tickets' : 'My Open Tickets' }} <span class="et-tab-count">{{ $mineCount }}</span></a>
    @endif
    @if($u->isAdmin() || $u->isSuperAdmin() || $u->isSalesManager())
        <a class="et-tab {{ $tab==='approvals'?'active':'' }}" href="{{ route('crm.estimate_tickets.index',['tab'=>'approvals']) }}" @if(($approvalsCount ?? 0) > 0) style="{{ $tab==='approvals' ? '' : 'background:#fdf4ff;color:#a21caf' }}" @endif><i class="fas fa-stamp"></i> Approvals <span class="et-tab-count" @if(($approvalsCount ?? 0) > 0 && $tab!=='approvals') style="background:#a21caf;color:#fff" @endif>{{ $approvalsCount ?? 0 }}</span></a>
    @endif
    <a class="et-tab {{ $tab==='history'?'active':'' }}" href="{{ route('crm.estimate_tickets.index',['tab'=>'history']) }}"><i class="fas fa-history"></i> History <span class="et-tab-count">{{ $historyCount }}</span></a>
</div>
<div class="et-card" style="padding:1rem;margin-bottom:1rem"><form id="estimateFilterForm" method="GET" style="display:flex;gap:.75rem;flex-wrap:wrap"><input type="hidden" name="tab" value="{{ $tab }}"><div style="position:relative;flex:1;min-width:220px"><i class="fas fa-search" style="position:absolute;left:13px;top:50%;transform:translateY(-50%);color:#94a3b8"></i><input id="estimateSearch" name="search" value="{{ request('search') }}" autocomplete="off" placeholder="Inquiry number, client or product" style="width:100%;box-sizing:border-box;padding:.7rem .7rem .7rem 2.4rem;border:1px solid #cbd5e1;border-radius:9px"></div><button class="et-btn"><i class="fas fa-search"></i> Search</button></form></div>
<div id="ticketResults" class="et-card" style="position:relative"><div id="ticketLoading" style="display:none;position:absolute;inset:0;z-index:5;background:rgba(255,255,255,.72);align-items:center;justify-content:center;color:var(--primary-purple);font-weight:800"><i class="fas fa-spinner fa-spin" style="margin-right:8px"></i> Searching...</div><div style="overflow-x:auto"><table class="et-table"><thead><tr><th>Ticket</th><th>Client / Product</th><th>Options</th><th>Estimator</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>
@forelse($tickets as $ticket)<tr class="et-ticket-row"><td><strong>{{ $ticket->ticket_number }}</strong></td><td><strong>{{ $ticket->client_name }}</strong><div style="color:#64748b;font-size:.82rem">{{ $ticket->product_style }}</div></td><td>{{ $ticket->options_count }} prices</td><td>{{ $u->isTeamLead() ? ($ticket->teamLead->name ?? 'Unassigned') : ($ticket->estimator->name ?? 'Unassigned') }}</td><td><span class="et-status s-{{ $ticket->status }}">{{ $ticket->status==='pending'?'New':ucwords(str_replace('_',' ',$ticket->status)) }}</span></td><td>{{ $ticket->created_at->format('M d, Y') }}</td><td>@if($tab==='active' && ($u->isEstimator() || $u->isTeamLead() || ($u->isAdmin() && optional($activeCrmWorkspace)->slug === 'mybox-packaging-app' && $ticket->status === 'pending')))<form method="POST" action="{{ route('crm.estimate_tickets.claim',$ticket->id) }}">{{ csrf_field() }}<button class="et-btn et-primary"><i class="fas fa-folder-open"></i> {{ $u->isTeamLead() ? 'Review Ticket' : 'Open Ticket' }}</button></form>@else<div style="display:flex;gap:6px"><a class="et-btn" href="{{ route('crm.estimate_tickets.show',$ticket->id) }}"><i class="fas fa-eye"></i> View</a>@if($ticket->status === 'returned_to_sales' && ($u->isAdmin() || $u->isSalesManager() || $u->isSales()))<a class="et-btn et-primary" href="{{ route('crm.estimate_tickets.edit',$ticket->id) }}"><i class="fas fa-edit"></i> Edit</a>@endif</div>@endif</td></tr>
@empty<tr><td colspan="7" style="text-align:center;padding:4rem;color:#94a3b8"><i class="fas fa-calculator" style="font-size:2.5rem;display:block;margin-bottom:1rem"></i>No estimate tickets yet.</td></tr>@endforelse
</tbody></table></div><div style="padding:1rem">{{ $tickets->appends(request()->query())->links() }}</div></div>
<script>
let estimateSearchTimer=null,estimateSearchController=null;
function loadEstimateTickets(url=null){const form=document.getElementById('estimateFilterForm'),params=new URLSearchParams(new FormData(form)),targetUrl=url||(`${window.location.pathname}?${params.toString()}`);if(estimateSearchController)estimateSearchController.abort();estimateSearchController=new AbortController();document.getElementById('ticketLoading').style.display='flex';fetch(targetUrl,{headers:{'X-Requested-With':'XMLHttpRequest'},signal:estimateSearchController.signal}).then(r=>r.text()).then(html=>{const doc=new DOMParser().parseFromString(html,'text/html'),fresh=doc.getElementById('ticketResults');if(fresh){document.getElementById('ticketResults').innerHTML=fresh.innerHTML;window.history.replaceState({},'',targetUrl)}}).catch(error=>{if(error.name!=='AbortError')console.error(error)}).finally(()=>{const loader=document.getElementById('ticketLoading');if(loader)loader.style.display='none'})}
document.getElementById('estimateSearch').addEventListener('input',()=>{clearTimeout(estimateSearchTimer);estimateSearchTimer=setTimeout(()=>loadEstimateTickets(),300)});
document.getElementById('estimateFilterForm').addEventListener('submit',event=>{event.preventDefault();loadEstimateTickets()});
document.addEventListener('click',event=>{const link=event.target.closest('#ticketResults .pagination a');if(link){event.preventDefault();loadEstimateTickets(link.href)}});
</script>
@endsection
